/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, Interface } from 'ethers';
import X402FlexSubscriptionsArtifact from '../../abi/X402FlexSubscriptions.json';
const _abi = X402FlexSubscriptionsArtifact.abi;
export class X402FlexSubscriptions__factory {
    static createInterface() {
        return new Interface(_abi);
    }
    static connect(address, runner) {
        return new Contract(address, _abi, runner);
    }
}
X402FlexSubscriptions__factory.abi = _abi;
