/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface } from 'ethers';
import type { ContractRunner } from 'ethers';
import X402FlexSubscriptionsArtifact from '../../abi/X402FlexSubscriptions.json';
import type {
  X402FlexSubscriptions,
  X402FlexSubscriptionsInterface,
} from '../X402FlexSubscriptions';

const _abi = X402FlexSubscriptionsArtifact.abi;

export class X402FlexSubscriptions__factory {
  static readonly abi = _abi;

  static createInterface(): X402FlexSubscriptionsInterface {
    return new Interface(_abi) as X402FlexSubscriptionsInterface;
  }

  static connect(address: string, runner?: ContractRunner | null): X402FlexSubscriptions {
    return new Contract(address, _abi, runner) as unknown as X402FlexSubscriptions;
  }
}
