/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace X402FlexRouter {
  export type PaymentIntentStruct = {
    paymentId: BytesLike;
    merchant: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    deadline: BigNumberish;
    payer: AddressLike;
    resourceId: BytesLike;
    referenceHash: BytesLike;
    nonce: BytesLike;
  };

  export type PaymentIntentStructOutput = [
    paymentId: string,
    merchant: string,
    token: string,
    amount: bigint,
    deadline: bigint,
    payer: string,
    resourceId: string,
    referenceHash: string,
    nonce: string
  ] & {
    paymentId: string;
    merchant: string;
    token: string;
    amount: bigint;
    deadline: bigint;
    payer: string;
    resourceId: string;
    referenceHash: string;
    nonce: string;
  };

  export type FlexWitnessStruct = {
    schemeId: BytesLike;
    intentHash: BytesLike;
    payer: AddressLike;
    salt: BytesLike;
  };

  export type FlexWitnessStructOutput = [
    schemeId: string,
    intentHash: string,
    payer: string,
    salt: string
  ] & { schemeId: string; intentHash: string; payer: string; salt: string };

  export type SessionContextStruct = {
    sessionId: BytesLike;
    agent: AddressLike;
  };

  export type SessionContextStructOutput = [
    sessionId: string,
    agent: string
  ] & { sessionId: string; agent: string };
}

export declare namespace SessionTypes {
  export type SessionSpendAuthStruct = {
    sessionId: BytesLike;
    intentHash: BytesLike;
    schemeId: BytesLike;
    spendNonce: BigNumberish;
    expiresAt: BigNumberish;
    epoch: BigNumberish;
  };

  export type SessionSpendAuthStructOutput = [
    sessionId: string,
    intentHash: string,
    schemeId: string,
    spendNonce: bigint,
    expiresAt: bigint,
    epoch: bigint
  ] & {
    sessionId: string;
    intentHash: string;
    schemeId: string;
    spendNonce: bigint;
    expiresAt: bigint;
    epoch: bigint;
  };
}

export declare namespace IPermit2 {
  export type TokenPermissionsStruct = {
    token: AddressLike;
    amount: BigNumberish;
  };

  export type TokenPermissionsStructOutput = [token: string, amount: bigint] & {
    token: string;
    amount: bigint;
  };

  export type PermitTransferFromStruct = {
    permitted: IPermit2.TokenPermissionsStruct;
    nonce: BigNumberish;
    deadline: BigNumberish;
  };

  export type PermitTransferFromStructOutput = [
    permitted: IPermit2.TokenPermissionsStructOutput,
    nonce: bigint,
    deadline: bigint
  ] & {
    permitted: IPermit2.TokenPermissionsStructOutput;
    nonce: bigint;
    deadline: bigint;
  };

  export type SignatureTransferDetailsStruct = {
    to: AddressLike;
    requestedAmount: BigNumberish;
  };

  export type SignatureTransferDetailsStructOutput = [
    to: string,
    requestedAmount: bigint
  ] & { to: string; requestedAmount: bigint };
}

export interface X402FlexRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "ROUTER_ADMIN"
      | "SCHEME_AA_PUSH"
      | "SCHEME_EIP2612"
      | "SCHEME_EIP3009"
      | "SCHEME_PERMIT2"
      | "cancel"
      | "cancelledIntent"
      | "cancelledPayment"
      | "depositAndSettleNative"
      | "depositAndSettleNativeSession"
      | "depositAndSettleToken"
      | "depositAndSettleTokenSession"
      | "eip712Domain"
      | "flexWitnessTypeString"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "hashFlexWitness"
      | "hashPaymentIntent"
      | "isSettled"
      | "pause"
      | "paused"
      | "payWithEIP2612"
      | "payWithEIP2612Session"
      | "payWithEIP3009"
      | "payWithEIP3009Session"
      | "payWithPermit2"
      | "payWithPermit2Session"
      | "permit2"
      | "permit2WitnessTypeString"
      | "registry"
      | "renounceRole"
      | "revokeRole"
      | "sessionStore"
      | "setSessionStore"
      | "settled"
      | "supportsInterface"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Cancelled"
      | "EIP712DomainChanged"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SessionStoreUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROUTER_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCHEME_AA_PUSH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCHEME_EIP2612",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCHEME_EIP3009",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCHEME_PERMIT2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [X402FlexRouter.PaymentIntentStruct, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelledIntent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelledPayment",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositAndSettleNative",
    values: [
      X402FlexRouter.PaymentIntentStruct,
      X402FlexRouter.FlexWitnessStruct,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositAndSettleNativeSession",
    values: [
      X402FlexRouter.PaymentIntentStruct,
      X402FlexRouter.FlexWitnessStruct,
      BytesLike,
      SessionTypes.SessionSpendAuthStruct,
      BytesLike,
      X402FlexRouter.SessionContextStruct,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositAndSettleToken",
    values: [
      X402FlexRouter.PaymentIntentStruct,
      X402FlexRouter.FlexWitnessStruct,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositAndSettleTokenSession",
    values: [
      X402FlexRouter.PaymentIntentStruct,
      X402FlexRouter.FlexWitnessStruct,
      BytesLike,
      SessionTypes.SessionSpendAuthStruct,
      BytesLike,
      X402FlexRouter.SessionContextStruct,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flexWitnessTypeString",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashFlexWitness",
    values: [X402FlexRouter.FlexWitnessStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "hashPaymentIntent",
    values: [X402FlexRouter.PaymentIntentStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isSettled",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payWithEIP2612",
    values: [
      X402FlexRouter.PaymentIntentStruct,
      X402FlexRouter.FlexWitnessStruct,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "payWithEIP2612Session",
    values: [
      X402FlexRouter.PaymentIntentStruct,
      X402FlexRouter.FlexWitnessStruct,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      SessionTypes.SessionSpendAuthStruct,
      BytesLike,
      X402FlexRouter.SessionContextStruct,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "payWithEIP3009",
    values: [
      X402FlexRouter.PaymentIntentStruct,
      X402FlexRouter.FlexWitnessStruct,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "payWithEIP3009Session",
    values: [
      X402FlexRouter.PaymentIntentStruct,
      X402FlexRouter.FlexWitnessStruct,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      SessionTypes.SessionSpendAuthStruct,
      BytesLike,
      X402FlexRouter.SessionContextStruct,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "payWithPermit2",
    values: [
      X402FlexRouter.PaymentIntentStruct,
      X402FlexRouter.FlexWitnessStruct,
      BytesLike,
      IPermit2.PermitTransferFromStruct,
      IPermit2.SignatureTransferDetailsStruct,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "payWithPermit2Session",
    values: [
      X402FlexRouter.PaymentIntentStruct,
      X402FlexRouter.FlexWitnessStruct,
      BytesLike,
      IPermit2.PermitTransferFromStruct,
      IPermit2.SignatureTransferDetailsStruct,
      BytesLike,
      SessionTypes.SessionSpendAuthStruct,
      BytesLike,
      X402FlexRouter.SessionContextStruct,
      string
    ]
  ): string;
  encodeFunctionData(functionFragment: "permit2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "permit2WitnessTypeString",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sessionStore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSessionStore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "settled", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROUTER_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCHEME_AA_PUSH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCHEME_EIP2612",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCHEME_EIP3009",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCHEME_PERMIT2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelledIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelledPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositAndSettleNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositAndSettleNativeSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositAndSettleToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositAndSettleTokenSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flexWitnessTypeString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashFlexWitness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashPaymentIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSettled", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payWithEIP2612",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payWithEIP2612Session",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payWithEIP3009",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payWithEIP3009Session",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payWithPermit2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payWithPermit2Session",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "permit2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "permit2WitnessTypeString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sessionStore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSessionStore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settled", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace CancelledEvent {
  export type InputTuple = [
    intentHash: BytesLike,
    paymentId: BytesLike,
    merchant: AddressLike,
    by: AddressLike,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    intentHash: string,
    paymentId: string,
    merchant: string,
    by: string,
    deadline: bigint
  ];
  export interface OutputObject {
    intentHash: string;
    paymentId: string;
    merchant: string;
    by: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionStoreUpdatedEvent {
  export type InputTuple = [previousStore: AddressLike, newStore: AddressLike];
  export type OutputTuple = [previousStore: string, newStore: string];
  export interface OutputObject {
    previousStore: string;
    newStore: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface X402FlexRouter extends BaseContract {
  connect(runner?: ContractRunner | null): X402FlexRouter;
  waitForDeployment(): Promise<this>;

  interface: X402FlexRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ROUTER_ADMIN: TypedContractMethod<[], [string], "view">;

  SCHEME_AA_PUSH: TypedContractMethod<[], [string], "view">;

  SCHEME_EIP2612: TypedContractMethod<[], [string], "view">;

  SCHEME_EIP3009: TypedContractMethod<[], [string], "view">;

  SCHEME_PERMIT2: TypedContractMethod<[], [string], "view">;

  cancel: TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      deadline: BigNumberish,
      sig: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  cancelledIntent: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  cancelledPayment: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [string],
    "view"
  >;

  depositAndSettleNative: TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      referenceData: string
    ],
    [void],
    "payable"
  >;

  depositAndSettleNativeSession: TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      auth: SessionTypes.SessionSpendAuthStruct,
      authSig: BytesLike,
      sessionCtx: X402FlexRouter.SessionContextStruct,
      referenceData: string
    ],
    [void],
    "payable"
  >;

  depositAndSettleToken: TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;

  depositAndSettleTokenSession: TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      auth: SessionTypes.SessionSpendAuthStruct,
      authSig: BytesLike,
      sessionCtx: X402FlexRouter.SessionContextStruct,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  flexWitnessTypeString: TypedContractMethod<[], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hashFlexWitness: TypedContractMethod<
    [witness: X402FlexRouter.FlexWitnessStruct],
    [string],
    "view"
  >;

  hashPaymentIntent: TypedContractMethod<
    [intent: X402FlexRouter.PaymentIntentStruct],
    [string],
    "view"
  >;

  isSettled: TypedContractMethod<
    [merchant: AddressLike, paymentId: BytesLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payWithEIP2612: TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      permitDeadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;

  payWithEIP2612Session: TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      permitDeadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      auth: SessionTypes.SessionSpendAuthStruct,
      authSig: BytesLike,
      sessionCtx: X402FlexRouter.SessionContextStruct,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;

  payWithEIP3009: TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      authNonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;

  payWithEIP3009Session: TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      authNonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      auth: SessionTypes.SessionSpendAuthStruct,
      authSig: BytesLike,
      sessionCtx: X402FlexRouter.SessionContextStruct,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;

  payWithPermit2: TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      permit: IPermit2.PermitTransferFromStruct,
      details: IPermit2.SignatureTransferDetailsStruct,
      signature: BytesLike,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;

  payWithPermit2Session: TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      permit: IPermit2.PermitTransferFromStruct,
      details: IPermit2.SignatureTransferDetailsStruct,
      signature: BytesLike,
      auth: SessionTypes.SessionSpendAuthStruct,
      authSig: BytesLike,
      sessionCtx: X402FlexRouter.SessionContextStruct,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;

  permit2: TypedContractMethod<[], [string], "view">;

  permit2WitnessTypeString: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  sessionStore: TypedContractMethod<[], [string], "view">;

  setSessionStore: TypedContractMethod<
    [newStore: AddressLike],
    [void],
    "nonpayable"
  >;

  settled: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROUTER_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SCHEME_AA_PUSH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SCHEME_EIP2612"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SCHEME_EIP3009"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SCHEME_PERMIT2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      deadline: BigNumberish,
      sig: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelledIntent"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "cancelledPayment"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositAndSettleNative"
  ): TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      referenceData: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositAndSettleNativeSession"
  ): TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      auth: SessionTypes.SessionSpendAuthStruct,
      authSig: BytesLike,
      sessionCtx: X402FlexRouter.SessionContextStruct,
      referenceData: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositAndSettleToken"
  ): TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositAndSettleTokenSession"
  ): TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      auth: SessionTypes.SessionSpendAuthStruct,
      authSig: BytesLike,
      sessionCtx: X402FlexRouter.SessionContextStruct,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "flexWitnessTypeString"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashFlexWitness"
  ): TypedContractMethod<
    [witness: X402FlexRouter.FlexWitnessStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashPaymentIntent"
  ): TypedContractMethod<
    [intent: X402FlexRouter.PaymentIntentStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSettled"
  ): TypedContractMethod<
    [merchant: AddressLike, paymentId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payWithEIP2612"
  ): TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      permitDeadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "payWithEIP2612Session"
  ): TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      permitDeadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      auth: SessionTypes.SessionSpendAuthStruct,
      authSig: BytesLike,
      sessionCtx: X402FlexRouter.SessionContextStruct,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "payWithEIP3009"
  ): TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      authNonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "payWithEIP3009Session"
  ): TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      authNonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      auth: SessionTypes.SessionSpendAuthStruct,
      authSig: BytesLike,
      sessionCtx: X402FlexRouter.SessionContextStruct,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "payWithPermit2"
  ): TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      permit: IPermit2.PermitTransferFromStruct,
      details: IPermit2.SignatureTransferDetailsStruct,
      signature: BytesLike,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "payWithPermit2Session"
  ): TypedContractMethod<
    [
      intent: X402FlexRouter.PaymentIntentStruct,
      witness: X402FlexRouter.FlexWitnessStruct,
      witnessSig: BytesLike,
      permit: IPermit2.PermitTransferFromStruct,
      details: IPermit2.SignatureTransferDetailsStruct,
      signature: BytesLike,
      auth: SessionTypes.SessionSpendAuthStruct,
      authSig: BytesLike,
      sessionCtx: X402FlexRouter.SessionContextStruct,
      referenceData: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "permit2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "permit2WitnessTypeString"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sessionStore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setSessionStore"
  ): TypedContractMethod<[newStore: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settled"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Cancelled"
  ): TypedContractEvent<
    CancelledEvent.InputTuple,
    CancelledEvent.OutputTuple,
    CancelledEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SessionStoreUpdated"
  ): TypedContractEvent<
    SessionStoreUpdatedEvent.InputTuple,
    SessionStoreUpdatedEvent.OutputTuple,
    SessionStoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "Cancelled(bytes32,bytes32,address,address,uint256)": TypedContractEvent<
      CancelledEvent.InputTuple,
      CancelledEvent.OutputTuple,
      CancelledEvent.OutputObject
    >;
    Cancelled: TypedContractEvent<
      CancelledEvent.InputTuple,
      CancelledEvent.OutputTuple,
      CancelledEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SessionStoreUpdated(address,address)": TypedContractEvent<
      SessionStoreUpdatedEvent.InputTuple,
      SessionStoreUpdatedEvent.OutputTuple,
      SessionStoreUpdatedEvent.OutputObject
    >;
    SessionStoreUpdated: TypedContractEvent<
      SessionStoreUpdatedEvent.InputTuple,
      SessionStoreUpdatedEvent.OutputTuple,
      SessionStoreUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
