/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SessionTypes {
  export type RateLimitStruct = {
    maxTxPerMinute: BigNumberish;
    maxTxPerDay: BigNumberish;
    coolDownSeconds: BigNumberish;
  };

  export type RateLimitStructOutput = [
    maxTxPerMinute: bigint,
    maxTxPerDay: bigint,
    coolDownSeconds: bigint
  ] & { maxTxPerMinute: bigint; maxTxPerDay: bigint; coolDownSeconds: bigint };

  export type TokenCapStruct = {
    token: AddressLike;
    cap: BigNumberish;
    dailyCap: BigNumberish;
  };

  export type TokenCapStructOutput = [
    token: string,
    cap: bigint,
    dailyCap: bigint
  ] & { token: string; cap: bigint; dailyCap: bigint };

  export type ClaimableSessionGrantStruct = {
    sessionId: BytesLike;
    payer: AddressLike;
    merchantScope: BytesLike;
    deadline: BigNumberish;
    expiresAt: BigNumberish;
    epoch: BigNumberish;
    nonce: BigNumberish;
    claimSigner: AddressLike;
    rateLimit: SessionTypes.RateLimitStruct;
    allowedSchemes: BytesLike[];
    tokenCaps: SessionTypes.TokenCapStruct[];
  };

  export type ClaimableSessionGrantStructOutput = [
    sessionId: string,
    payer: string,
    merchantScope: string,
    deadline: bigint,
    expiresAt: bigint,
    epoch: bigint,
    nonce: bigint,
    claimSigner: string,
    rateLimit: SessionTypes.RateLimitStructOutput,
    allowedSchemes: string[],
    tokenCaps: SessionTypes.TokenCapStructOutput[]
  ] & {
    sessionId: string;
    payer: string;
    merchantScope: string;
    deadline: bigint;
    expiresAt: bigint;
    epoch: bigint;
    nonce: bigint;
    claimSigner: string;
    rateLimit: SessionTypes.RateLimitStructOutput;
    allowedSchemes: string[];
    tokenCaps: SessionTypes.TokenCapStructOutput[];
  };

  export type FlexSessionGrantStruct = {
    sessionId: BytesLike;
    payer: AddressLike;
    agent: AddressLike;
    merchantScope: BytesLike;
    deadline: BigNumberish;
    expiresAt: BigNumberish;
    epoch: BigNumberish;
    nonce: BigNumberish;
    rateLimit: SessionTypes.RateLimitStruct;
    allowedSchemes: BytesLike[];
    tokenCaps: SessionTypes.TokenCapStruct[];
  };

  export type FlexSessionGrantStructOutput = [
    sessionId: string,
    payer: string,
    agent: string,
    merchantScope: string,
    deadline: bigint,
    expiresAt: bigint,
    epoch: bigint,
    nonce: bigint,
    rateLimit: SessionTypes.RateLimitStructOutput,
    allowedSchemes: string[],
    tokenCaps: SessionTypes.TokenCapStructOutput[]
  ] & {
    sessionId: string;
    payer: string;
    agent: string;
    merchantScope: string;
    deadline: bigint;
    expiresAt: bigint;
    epoch: bigint;
    nonce: bigint;
    rateLimit: SessionTypes.RateLimitStructOutput;
    allowedSchemes: string[];
    tokenCaps: SessionTypes.TokenCapStructOutput[];
  };
}

export declare namespace X402FlexSessionStore {
  export type SessionStateStruct = {
    initialized: boolean;
    payer: AddressLike;
    agent: AddressLike;
    merchantScope: BytesLike;
    expiresAt: BigNumberish;
    epoch: BigNumberish;
    nonce: BigNumberish;
    revoked: boolean;
    rateLimit: SessionTypes.RateLimitStruct;
    minuteWindowStart: BigNumberish;
    txCountInMinute: BigNumberish;
    dayWindowStart: BigNumberish;
    txCountInDay: BigNumberish;
    lastSpendAt: BigNumberish;
  };

  export type SessionStateStructOutput = [
    initialized: boolean,
    payer: string,
    agent: string,
    merchantScope: string,
    expiresAt: bigint,
    epoch: bigint,
    nonce: bigint,
    revoked: boolean,
    rateLimit: SessionTypes.RateLimitStructOutput,
    minuteWindowStart: bigint,
    txCountInMinute: bigint,
    dayWindowStart: bigint,
    txCountInDay: bigint,
    lastSpendAt: bigint
  ] & {
    initialized: boolean;
    payer: string;
    agent: string;
    merchantScope: string;
    expiresAt: bigint;
    epoch: bigint;
    nonce: bigint;
    revoked: boolean;
    rateLimit: SessionTypes.RateLimitStructOutput;
    minuteWindowStart: bigint;
    txCountInMinute: bigint;
    dayWindowStart: bigint;
    txCountInDay: bigint;
    lastSpendAt: bigint;
  };

  export type SpendRequestStruct = {
    sessionId: BytesLike;
    agent: AddressLike;
    merchant: AddressLike;
    resourceId: BytesLike;
    token: AddressLike;
    tokenAmount: BigNumberish;
    schemeId: BytesLike;
  };

  export type SpendRequestStructOutput = [
    sessionId: string,
    agent: string,
    merchant: string,
    resourceId: string,
    token: string,
    tokenAmount: bigint,
    schemeId: string
  ] & {
    sessionId: string;
    agent: string;
    merchant: string;
    resourceId: string;
    token: string;
    tokenAmount: bigint;
    schemeId: string;
  };

  export type TokenBucketStruct = {
    cap: BigNumberish;
    remaining: BigNumberish;
    dailyCap: BigNumberish;
    dailySpent: BigNumberish;
    dailyWindowStart: BigNumberish;
  };

  export type TokenBucketStructOutput = [
    cap: bigint,
    remaining: bigint,
    dailyCap: bigint,
    dailySpent: bigint,
    dailyWindowStart: bigint
  ] & {
    cap: bigint;
    remaining: bigint;
    dailyCap: bigint;
    dailySpent: bigint;
    dailyWindowStart: bigint;
  };
}

export interface X402FlexSessionStoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "ROUTER_ROLE"
      | "claimSession"
      | "consumeSpendNonce"
      | "eip712Domain"
      | "getClaimSigner"
      | "getRoleAdmin"
      | "getSession"
      | "getSessionSpendNonce"
      | "getSessionState"
      | "grantRole"
      | "hasRole"
      | "isClaimableSession"
      | "openClaimableSession"
      | "openSession"
      | "renounceRole"
      | "revokeRole"
      | "revokeSession"
      | "revokeSessionBySig"
      | "router"
      | "setRouter"
      | "spendFromSession"
      | "supportsInterface"
      | "tokenBudget"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EIP712DomainChanged"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "RouterUpdated"
      | "SessionClaimableOpened"
      | "SessionClaimed"
      | "SessionOpened"
      | "SessionRevoked"
      | "SessionSpent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROUTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimSession",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "consumeSpendNonce",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimSigner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSession",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSessionSpendNonce",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSessionState",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isClaimableSession",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openClaimableSession",
    values: [SessionTypes.ClaimableSessionGrantStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openSession",
    values: [SessionTypes.FlexSessionGrantStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeSession",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeSessionBySig",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "spendFromSession",
    values: [X402FlexSessionStore.SpendRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBudget",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROUTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consumeSpendNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSession", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSessionSpendNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSessionState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isClaimableSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openClaimableSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeSessionBySig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "spendFromSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBudget",
    data: BytesLike
  ): Result;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouterUpdatedEvent {
  export type InputTuple = [router: AddressLike];
  export type OutputTuple = [router: string];
  export interface OutputObject {
    router: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionClaimableOpenedEvent {
  export type InputTuple = [
    sessionId: BytesLike,
    payer: AddressLike,
    claimSigner: AddressLike,
    epoch: BigNumberish
  ];
  export type OutputTuple = [
    sessionId: string,
    payer: string,
    claimSigner: string,
    epoch: bigint
  ];
  export interface OutputObject {
    sessionId: string;
    payer: string;
    claimSigner: string;
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionClaimedEvent {
  export type InputTuple = [
    sessionId: BytesLike,
    payer: AddressLike,
    agent: AddressLike,
    epoch: BigNumberish
  ];
  export type OutputTuple = [
    sessionId: string,
    payer: string,
    agent: string,
    epoch: bigint
  ];
  export interface OutputObject {
    sessionId: string;
    payer: string;
    agent: string;
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionOpenedEvent {
  export type InputTuple = [
    sessionId: BytesLike,
    payer: AddressLike,
    agent: AddressLike,
    expiresAt: BigNumberish,
    epoch: BigNumberish,
    merchantScope: BytesLike
  ];
  export type OutputTuple = [
    sessionId: string,
    payer: string,
    agent: string,
    expiresAt: bigint,
    epoch: bigint,
    merchantScope: string
  ];
  export interface OutputObject {
    sessionId: string;
    payer: string;
    agent: string;
    expiresAt: bigint;
    epoch: bigint;
    merchantScope: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionRevokedEvent {
  export type InputTuple = [
    sessionId: BytesLike,
    caller: AddressLike,
    epoch: BigNumberish
  ];
  export type OutputTuple = [sessionId: string, caller: string, epoch: bigint];
  export interface OutputObject {
    sessionId: string;
    caller: string;
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionSpentEvent {
  export type InputTuple = [
    sessionId: BytesLike,
    agent: AddressLike,
    token: AddressLike,
    tokenAmount: BigNumberish,
    schemeId: BytesLike
  ];
  export type OutputTuple = [
    sessionId: string,
    agent: string,
    token: string,
    tokenAmount: bigint,
    schemeId: string
  ];
  export interface OutputObject {
    sessionId: string;
    agent: string;
    token: string;
    tokenAmount: bigint;
    schemeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface X402FlexSessionStore extends BaseContract {
  connect(runner?: ContractRunner | null): X402FlexSessionStore;
  waitForDeployment(): Promise<this>;

  interface: X402FlexSessionStoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ROUTER_ROLE: TypedContractMethod<[], [string], "view">;

  claimSession: TypedContractMethod<
    [
      sessionId: BytesLike,
      agent: AddressLike,
      deadline: BigNumberish,
      claimSig: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  consumeSpendNonce: TypedContractMethod<
    [sessionId: BytesLike, expected: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  getClaimSigner: TypedContractMethod<[sessionId: BytesLike], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSession: TypedContractMethod<
    [sessionId: BytesLike],
    [
      [X402FlexSessionStore.SessionStateStructOutput, string[], string[]] & {
        info: X402FlexSessionStore.SessionStateStructOutput;
        tokens: string[];
        schemes: string[];
      }
    ],
    "view"
  >;

  getSessionSpendNonce: TypedContractMethod<
    [sessionId: BytesLike],
    [bigint],
    "view"
  >;

  getSessionState: TypedContractMethod<
    [sessionId: BytesLike],
    [X402FlexSessionStore.SessionStateStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isClaimableSession: TypedContractMethod<
    [sessionId: BytesLike],
    [boolean],
    "view"
  >;

  openClaimableSession: TypedContractMethod<
    [grant: SessionTypes.ClaimableSessionGrantStruct, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  openSession: TypedContractMethod<
    [grant: SessionTypes.FlexSessionGrantStruct, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeSession: TypedContractMethod<
    [sessionId: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeSessionBySig: TypedContractMethod<
    [sessionId: BytesLike, deadline: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  router: TypedContractMethod<[], [string], "view">;

  setRouter: TypedContractMethod<
    [newRouter: AddressLike],
    [void],
    "nonpayable"
  >;

  spendFromSession: TypedContractMethod<
    [request: X402FlexSessionStore.SpendRequestStruct],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tokenBudget: TypedContractMethod<
    [sessionId: BytesLike, token: AddressLike],
    [X402FlexSessionStore.TokenBucketStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROUTER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimSession"
  ): TypedContractMethod<
    [
      sessionId: BytesLike,
      agent: AddressLike,
      deadline: BigNumberish,
      claimSig: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "consumeSpendNonce"
  ): TypedContractMethod<
    [sessionId: BytesLike, expected: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaimSigner"
  ): TypedContractMethod<[sessionId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSession"
  ): TypedContractMethod<
    [sessionId: BytesLike],
    [
      [X402FlexSessionStore.SessionStateStructOutput, string[], string[]] & {
        info: X402FlexSessionStore.SessionStateStructOutput;
        tokens: string[];
        schemes: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSessionSpendNonce"
  ): TypedContractMethod<[sessionId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSessionState"
  ): TypedContractMethod<
    [sessionId: BytesLike],
    [X402FlexSessionStore.SessionStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isClaimableSession"
  ): TypedContractMethod<[sessionId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "openClaimableSession"
  ): TypedContractMethod<
    [grant: SessionTypes.ClaimableSessionGrantStruct, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "openSession"
  ): TypedContractMethod<
    [grant: SessionTypes.FlexSessionGrantStruct, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeSession"
  ): TypedContractMethod<[sessionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeSessionBySig"
  ): TypedContractMethod<
    [sessionId: BytesLike, deadline: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "router"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setRouter"
  ): TypedContractMethod<[newRouter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "spendFromSession"
  ): TypedContractMethod<
    [request: X402FlexSessionStore.SpendRequestStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenBudget"
  ): TypedContractMethod<
    [sessionId: BytesLike, token: AddressLike],
    [X402FlexSessionStore.TokenBucketStructOutput],
    "view"
  >;

  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RouterUpdated"
  ): TypedContractEvent<
    RouterUpdatedEvent.InputTuple,
    RouterUpdatedEvent.OutputTuple,
    RouterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SessionClaimableOpened"
  ): TypedContractEvent<
    SessionClaimableOpenedEvent.InputTuple,
    SessionClaimableOpenedEvent.OutputTuple,
    SessionClaimableOpenedEvent.OutputObject
  >;
  getEvent(
    key: "SessionClaimed"
  ): TypedContractEvent<
    SessionClaimedEvent.InputTuple,
    SessionClaimedEvent.OutputTuple,
    SessionClaimedEvent.OutputObject
  >;
  getEvent(
    key: "SessionOpened"
  ): TypedContractEvent<
    SessionOpenedEvent.InputTuple,
    SessionOpenedEvent.OutputTuple,
    SessionOpenedEvent.OutputObject
  >;
  getEvent(
    key: "SessionRevoked"
  ): TypedContractEvent<
    SessionRevokedEvent.InputTuple,
    SessionRevokedEvent.OutputTuple,
    SessionRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SessionSpent"
  ): TypedContractEvent<
    SessionSpentEvent.InputTuple,
    SessionSpentEvent.OutputTuple,
    SessionSpentEvent.OutputObject
  >;

  filters: {
    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "RouterUpdated(address)": TypedContractEvent<
      RouterUpdatedEvent.InputTuple,
      RouterUpdatedEvent.OutputTuple,
      RouterUpdatedEvent.OutputObject
    >;
    RouterUpdated: TypedContractEvent<
      RouterUpdatedEvent.InputTuple,
      RouterUpdatedEvent.OutputTuple,
      RouterUpdatedEvent.OutputObject
    >;

    "SessionClaimableOpened(bytes32,address,address,uint32)": TypedContractEvent<
      SessionClaimableOpenedEvent.InputTuple,
      SessionClaimableOpenedEvent.OutputTuple,
      SessionClaimableOpenedEvent.OutputObject
    >;
    SessionClaimableOpened: TypedContractEvent<
      SessionClaimableOpenedEvent.InputTuple,
      SessionClaimableOpenedEvent.OutputTuple,
      SessionClaimableOpenedEvent.OutputObject
    >;

    "SessionClaimed(bytes32,address,address,uint32)": TypedContractEvent<
      SessionClaimedEvent.InputTuple,
      SessionClaimedEvent.OutputTuple,
      SessionClaimedEvent.OutputObject
    >;
    SessionClaimed: TypedContractEvent<
      SessionClaimedEvent.InputTuple,
      SessionClaimedEvent.OutputTuple,
      SessionClaimedEvent.OutputObject
    >;

    "SessionOpened(bytes32,address,address,uint32,uint32,bytes32)": TypedContractEvent<
      SessionOpenedEvent.InputTuple,
      SessionOpenedEvent.OutputTuple,
      SessionOpenedEvent.OutputObject
    >;
    SessionOpened: TypedContractEvent<
      SessionOpenedEvent.InputTuple,
      SessionOpenedEvent.OutputTuple,
      SessionOpenedEvent.OutputObject
    >;

    "SessionRevoked(bytes32,address,uint32)": TypedContractEvent<
      SessionRevokedEvent.InputTuple,
      SessionRevokedEvent.OutputTuple,
      SessionRevokedEvent.OutputObject
    >;
    SessionRevoked: TypedContractEvent<
      SessionRevokedEvent.InputTuple,
      SessionRevokedEvent.OutputTuple,
      SessionRevokedEvent.OutputObject
    >;

    "SessionSpent(bytes32,address,address,uint256,bytes32)": TypedContractEvent<
      SessionSpentEvent.InputTuple,
      SessionSpentEvent.OutputTuple,
      SessionSpentEvent.OutputObject
    >;
    SessionSpent: TypedContractEvent<
      SessionSpentEvent.InputTuple,
      SessionSpentEvent.OutputTuple,
      SessionSpentEvent.OutputObject
    >;
  };
}
