/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  AddressLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
} from 'ethers';
import type { TypedContractMethod } from './common';

export declare namespace X402FlexSubscriptions {
  export type CreateSubArgsStruct = {
    payer: AddressLike;
    merchant: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    startAt: BigNumberish;
    cadenceKind: BigNumberish;
    cadence: BigNumberish;
    cancelWindow: BigNumberish;
    maxPayments: BigNumberish;
    pullMode: BigNumberish;
    termsHash: BytesLike;
    salt: BytesLike;
    deadline: BigNumberish;
  };

  export type SubscriptionStructOutput = [
    payer: string,
    merchant: string,
    token: string,
    amount: bigint,
    nextChargeAt: bigint,
    lastChargedAt: bigint,
    cadence: bigint,
    cancelWindow: bigint,
    maxPayments: bigint,
    paymentsMade: bigint,
    status: bigint,
    cadenceKind: bigint,
    pullMode: bigint,
    termsHash: string
  ] & {
    payer: string;
    merchant: string;
    token: string;
    amount: bigint;
    nextChargeAt: bigint;
    lastChargedAt: bigint;
    cadence: bigint;
    cancelWindow: bigint;
    maxPayments: bigint;
    paymentsMade: bigint;
    status: bigint;
    cadenceKind: bigint;
    pullMode: bigint;
    termsHash: string;
  };
}

export interface X402FlexSubscriptionsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'cancel'
      | 'cancelBySig'
      | 'charge'
      | 'computeSubId'
      | 'createSubscriptionWithSig'
      | 'getSubscription'
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'cancel', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'cancelBySig', values: [BytesLike, BigNumberish, BytesLike]): string;
  encodeFunctionData(functionFragment: 'charge', values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: 'computeSubId',
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
    ]
  ): string;
  encodeFunctionData(
    functionFragment: 'createSubscriptionWithSig',
    values: [X402FlexSubscriptions.CreateSubArgsStruct, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: 'getSubscription', values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: 'cancel', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'cancelBySig', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'charge', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'computeSubId', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createSubscriptionWithSig', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getSubscription', data: BytesLike): Result;
}

export interface X402FlexSubscriptions extends BaseContract {
  connect(runner?: ContractRunner | null): X402FlexSubscriptions;
  waitForDeployment(): Promise<this>;

  interface: X402FlexSubscriptionsInterface;

  cancel: TypedContractMethod<[subId: BytesLike], [void], 'nonpayable'>;

  cancelBySig: TypedContractMethod<
    [subId: BytesLike, deadline: BigNumberish, sig: BytesLike],
    [void],
    'nonpayable'
  >;

  charge: TypedContractMethod<[subId: BytesLike], [void], 'nonpayable'>;

  computeSubId: TypedContractMethod<
    [
      payer: AddressLike,
      merchant: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      startAt: BigNumberish,
      cadenceKind: BigNumberish,
      cadence: BigNumberish,
      cancelWindow: BigNumberish,
      maxPayments: BigNumberish,
      pullMode: BigNumberish,
      termsHash: BytesLike,
      salt: BytesLike,
    ],
    [string],
    'view'
  >;

  createSubscriptionWithSig: TypedContractMethod<
    [a: X402FlexSubscriptions.CreateSubArgsStruct, payerSig: BytesLike],
    [string],
    'nonpayable'
  >;

  getSubscription: TypedContractMethod<[subId: BytesLike], [X402FlexSubscriptions.SubscriptionStructOutput], 'view'>;
}
